### PR TITLE
Add funding file

### PR DESCRIPTION
**Pull request by webknjaz**
Ref: https://github.com/sponsors

### CODE REVIEW

**Comment by Psycojoker** [comment]
Ah great, thx a lot :)

**Comment by webknjaz** [comment]
@Psycojoker for the button to show up, you need to go to the project settings and enable it.

**Comment by Psycojoker** [comment]
@webknjaz done, thx :) (sorry, I'm a bit in the middle of so much things :sweat_smile:)

**Comment by webknjaz** [comment]
Oh that's fine. Just wanted to give you a hint :)

**Pull request merged**
