### PR TITLE
Support Python 3.7

### PR DESCRIPTION
**Pull request by BugDiver**
Ref #164

### CODE REVIEW

**Comment by scottbelden** [comment]
What would it take to get this merged in? I noticed a test failed. Is the failure the reason there hasn't been any comment on here yet?

**Comment by Psycojoker** [comment]
No, just that I'm super busy and already working on including new python3 feature in Baron (in addition of everything else in my life) before taking a look at RedBaron, sorry :/

The failed test seems to be coming from the fact that Baron supports new nodes that aren't yet in RedBaron, thats not related to this feature.

At a quick look it would be better to have this compatibility sorted at the top level of the file at the import level but I generally fix those minor details myself instead of asking people to do it.

**Comment by scottbelden** [comment]
Is there any simple work that I could try to help with or is most of it deep in the weeds and would be better to wait on you to find time?

Thanks again for this tool!

**Comment by gasparka** [comment]
For information, yesterday Arch-linux updated the system Python to 3.7.

**Comment by Psycojoker** [comment]
A release is coming in the next days :)

I think I only need to finish the documentation and maybe fix some other bugs (but this project loves to keep popping new like it's never ending so I can't promise anything >.>)

> Is there any simple work that I could try to help with or is most of it deep in the weeds and would be better to wait on you to find time?

It's a bit hard to tell :confused: ... I'm finally back on this project after some years so I don't have the full global picture in mind and it's, sadly, a very complicated project. If you want we can talk about it on IRC but I'm not sure I'll find simple work for now (as I need to get back in track before being able to peacefully delegate) except if you want to write documentation.

I'm going to see if there is way to get a bit of financing for this project, it takes a LOT of time to work, that would allow me to put it more into it and make this project more reliable for the future (since apparently it has started to get way more users than when I've stopped working on it).

**Comment by Psycojoker** [comment]
0.7 has been release.

**Pull request merged**
